language: node_js
sudo: required
dist: trusty

git:
  depth: 5

branches:
  only:
    - master
    - /^rc-.*$/
    - /^[0-9]+\.[0-9]+\.[0-9]+.*/

cache:
  directories:
    - node_modules

before_install:
  - npm install -g @angular/cli

script:
  - ng lint

after_success:
  - npm run build
  - cd dist
  - bash <(curl -s https://giftdibs.github.io/giftdibs-ci/publish.sh)
